version: '2'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /nginx-manager/config.json:/app/config/production.json
      - /nginx-manager/data:/data
      - /nginx-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
      # if you want pretty colors in your docker logs:
      - FORCE_COLOR: 1
      - database.engine: "mysql"
      - database.host: db
      - database.name: "npm"
      - database.user: "npm"
      - database.password: "npm"
      - database.port: 3306
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /nginx-manager/data/mysql:/var/lib/mysql
volumes:
  db_data:
  app: