version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /nginx-manager/config.json:/app/config/production.json
      - /nginx-manager/data:/data
      - /nginx-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
      # if you want pretty colors in your docker logs:
      - FORCE_COLOR: 1

  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - /nginx-manager/data/mysql:/var/lib/mysql
