version: '2'

services:
  db:
    image: mongo
    volumes:
      - ./db:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: strapi

  strapi:
    image: strapi/strapi:latest
    ports:
      - 80:1337
    restart: always
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_NAME: strapi
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      DATABASE_AUTHENTICATION_DATABASE: strapi
    volumes:
      - app:/srv/app
    depends_on:
      - db

volumes:
  db_data:
  app:
