version: '2'

services:
   db:
     image: mysql
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
     command: --default-authentication-plugin=mysql_native_password

   strapi:
     image: strapi/strapi:latest
     ports:
       - 80:1337
     restart: always
     environment:
        DATABASE_CLIENT: mysql
        DATABASE_HOST: db
        DATABASE_PORT: 3306
        DATABASE_NAME: strapi
        DATABASE_USERNAME: strapi
        DATABASE_PASSWORD: strapi
     volumes:
      - app:/srv/app
     depends_on:
      - db

volumes:
    db_data:
    app:
